# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: 'Operations'
  items:
    - label: 'GetAxieBriefList'
      link: '/operations/getAxieBriefList'
- label: More
  items:
    - label: 'BetterAxie'
      link: https://better-axie.web.app/
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
